server:
  port: 8080

spring:
  application:
    name: lime-it-broker-app
  config:
    import: >
      jackson.yml,
      lime-it-broker.yml, 
      web-client.yml,
      timer.yml
  profiles:
    active: local
  cloud:
    config:
      enabled: false

logging:
  level:
    com.lime.it.lime.it.broker: INFO

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info, health