server:
  port: 8080

spring:
  application:
    name: lime-it-broker-app
  config:
    import: >
      lime-it-broker.yml, 
      web-client.yml
  jackson:
    deserialization:
      accept-single-value-as-array: true
      fail-on-unknown-properties: false
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null
  cloud:
    config:
      enabled: false

logging:
  level:
    com.lime.it.lime.it.broker: INFO

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info, health