spring:
  jackson:
    deserialization:
      accept-single-value-as-array: true
      fail-on-unknown-properties: false
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null